### ISSUE TITLE
Controller UI menus

### ISSUE THREAD

**Issue by TheRevilo2018** [VEX-Robotics-SDSMT/VEXU2022-2023#2]
Using controller menus will allow us to have multiple branches in the code on startup so that each robot can have only one project. This will reduce upload errors and allow our code to be much more flexible and easy to modify.

a possible interface for the constructor in order to set up this UI might look like this:

ControllerUI(string prompt, Array<Pair<string, Action>> buttonList)

**Comment by BHenderson21** [comment]
The basic functionality of the controller UI menu options has been written, tested, and implemented into the main branch. This functionality should be transferred to a member function for a class that needs to be made for ease of expansion of this functionality to more options in the future.
